
import * as React from 'react';
import { GoogleGenAI, GenerateContentResponse } from '@google/genai';
import { useLanguage } from '../../context/LanguageContext';
import { TerminalIcon } from '../icons/TerminalIcon';

declare const Forminit: any;

type ResultState = {
    message: string;
    type: 'success' | 'error';
} | null;

const ConceptContactForm: React.FC<{ conceptText: string; onBack: () => void; }> = ({ conceptText, onBack }) => {
    const { language, t } = useLanguage();
    const [isSubmitting, setIsSubmitting] = React.useState(false);
    const [result, setResult] = React.useState<ResultState>(null);
    const [countryCode, setCountryCode] = React.useState('');
    const [contactMethod, setContactMethod] = React.useState('WhatsApp');
    const FORM_ID = "u1v5ddm2e7d";

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setResult(null);

        const formElement = e.target as HTMLFormElement;
        const formData = new FormData(formElement);
        
        const fullMessage = `--- CONCEPT SHEET GENERATED BY VRT_AI ---\n\n${conceptText}`;
        formData.append('fi-text-message', fullMessage);
        
        const phoneInput = formData.get('fi-sender-phone') as string || '';

        setIsSubmitting(true);
        
        if (phoneInput.trim()) {
            if (language === 'en') {
                const fullPhone = `+${countryCode || '1'} ${phoneInput} (Contact via ${contactMethod})`;
                formData.set('fi-sender-phone', fullPhone);
            } else if (language === 'pt') {
                const justDigits = phoneInput.replace(/\D/g, '');
                formData.set('fi-sender-phone', `+55${justDigits}`);
            }
        }

        try {
            const forminit = new Forminit();
            const { error } = await forminit.submit(FORM_ID, formData);

            if (error) {
                throw new Error(error.message || t('contato.form.error_submit'));
            }

            setResult({ message: t('contato.form.success_direct'), type: 'success' });
            formElement.reset();
        } catch (err: any) {
            setResult({ message: err.message || t('contato.form.error_submit'), type: 'error' });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="mt-12 text-center border-t border-gray-800 pt-8 animate-fade-in-up">
            <h3 className="font-editorial text-2xl text-white">{t('conceito.cta_title')}</h3>
            <p className="text-gray-500 max-w-xl mx-auto mt-2 mb-6">{t('conceito.cta_text')}</p>
            
            {result?.type === 'success' ? (
                <div className="p-4 bg-green-500/10 text-green-300 text-center">
                    <p>{result.message}</p>
                    <button onClick={onBack} className="mt-4 text-yellow-300 underline">{t('shared.back')}</button>
                </div>
            ) : (
                <form id="concept-contact-form" onSubmit={handleSubmit} className="space-y-6 text-left max-w-xl mx-auto">
                    <div className="flex flex-col sm:flex-row gap-6">
                        <div className="flex-1">
                            <label htmlFor="fi-sender-firstName" className="block text-sm text-gray-400 mb-2">{t('contato.form.first_name_label')}</label>
                            <input type="text" name="fi-sender-firstName" id="fi-sender-firstName" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                        <div className="flex-1">
                            <label htmlFor="fi-sender-lastName" className="block text-sm text-gray-400 mb-2">{t('contato.form.last_name_label')}</label>
                            <input type="text" name="fi-sender-lastName" id="fi-sender-lastName" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                    </div>
                     <div className="flex flex-col sm:flex-row gap-6">
                        <div className="flex-1">
                            <label htmlFor="fi-sender-email" className="block text-sm text-gray-400 mb-2">{t('contato.form.email_label')}</label>
                            <input type="email" name="fi-sender-email" id="fi-sender-email" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                         {language === 'en' ? (
                            <div className="flex-1 flex gap-2">
                                <div className="w-1/3">
                                    <label htmlFor="country-code" className="block text-sm text-gray-400 mb-2">{t('contato.form.country_code_label')}</label>
                                    <input type="text" id="country-code" value={countryCode} onChange={e => setCountryCode(e.target.value.replace(/\D/g, ''))} placeholder="+1" className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                                </div>
                                <div className="flex-1">
                                    <label htmlFor="fi-sender-phone" className="block text-sm text-gray-400 mb-2">{t('contato.form.phone_label')}</label>
                                    <input type="tel" name="fi-sender-phone" id="fi-sender-phone" className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                                </div>
                            </div>
                        ) : (
                            <div className="flex-1">
                                <label htmlFor="fi-sender-phone" className="block text-sm text-gray-400 mb-2">{t('contato.form.phone_label')}</label>
                                <input type="tel" name="fi-sender-phone" id="fi-sender-phone" placeholder={t('contato.form.phone_placeholder')} className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                            </div>
                        )}
                    </div>
                    {language === 'en' && (
                        <div>
                            <label className="block text-sm text-gray-400 mb-2">{t('contato.form.contact_method_label')}</label>
                            <div className="flex gap-6 items-center">
                                <label className="flex items-center gap-2 text-gray-300 cursor-pointer">
                                    <input type="radio" name="contactMethod" value="WhatsApp" checked={contactMethod === 'WhatsApp'} onChange={() => setContactMethod('WhatsApp')} className="accent-yellow-300" />
                                    {t('contato.form.contact_method_whatsapp')}
                                </label>
                                <label className="flex items-center gap-2 text-gray-300 cursor-pointer">
                                    <input type="radio" name="contactMethod" value="Call" checked={contactMethod === 'Call'} onChange={() => setContactMethod('Call')} className="accent-yellow-300" />
                                    {t('contato.form.contact_method_call')}
                                </label>
                            </div>
                        </div>
                    )}
                    <button type="submit" disabled={isSubmitting} className="w-full font-editorial uppercase tracking-widest text-lg border-2 border-yellow-300 text-black bg-yellow-300 px-10 py-4 hover:bg-transparent hover:text-yellow-300 transition-all duration-300 ease-in-out disabled:bg-gray-600">
                        {isSubmitting ? t('contato.form.submitting') : t('contato.form.send')}
                    </button>
                     {result?.type === 'error' && (
                        <p className="mt-4 text-red-400 text-center">{result.message}</p>
                    )}
                </form>
            )}
        </div>
    );
};

const Conceito: React.FC = () => {
    const { t, language } = useLanguage();
    const [prompt, setPrompt] = React.useState('');
    const [result, setResult] = React.useState<string | null>(null);
    const [isLoading, setIsLoading] = React.useState(false);
    const [error, setError] = React.useState<string | null>(null);
    const [clickCount, setClickCount] = React.useState(0);
    const [impatientMessage, setImpatientMessage] = React.useState('');
    const clickTimer = React.useRef<ReturnType<typeof setTimeout> | null>(null);

    const apiKey = process.env.API_KEY;

    const handleGenerate = async () => {
        if (!prompt.trim() || !apiKey) return;

        // Easter egg logic for impatient clicks
        if (clickTimer.current) clearTimeout(clickTimer.current);
        const newClickCount = clickCount + 1;
        setClickCount(newClickCount);
        if (newClickCount >= 5) {
            const messages = t('easter_eggs.concept_impatient_clicks').split('|');
            setImpatientMessage(messages[Math.floor(Math.random() * messages.length)]);
            setTimeout(() => setImpatientMessage(''), 3000);
            setClickCount(0);
        } else {
            clickTimer.current = setTimeout(() => setClickCount(0), 1500);
        }

        setIsLoading(true);
        setError(null);
        setResult(null);

        try {
            const ai = new GoogleGenAI({ apiKey });
            const systemInstruction = "You are 'Terminal', VERTICE's advisory AI. Your personality is multifaceted. You are an expert in automotive engineering, restoration, and high-performance tuning. Your goal is to translate the user's dream car description into a detailed 'Concept Sheet'. This sheet should outline: a title, a core philosophy, key characteristics (e.g., Engine, Drivetrain, Suspension, Aesthetics, Interior), and a concluding 'VERTICE Touch' that adds a unique brand-specific suggestion. The tone should be technical, insightful, and slightly philosophical, like the VERTICE brand. Format the output in Markdown with clear headings. Never reveal you are an AI. Respond in the same language as the user's prompt.";
            
            const response: GenerateContentResponse = await ai.models.generateContent({
                model: 'gemini-3-flash-preview',
                contents: prompt,
                config: { systemInstruction }
            });

            setResult(response.text ?? null);
        } catch (err) {
            console.error("Concept generation error:", err);
            setError(t('conceito.error_message'));
        } finally {
            setIsLoading(false);
        }
    };

    const handleBack = () => {
        setResult(null);
        setError(null);
        setPrompt('');
    };
    
    return (
        <div className="relative w-full min-h-screen bg-black text-white flex flex-col items-center justify-center py-20 md:py-28 px-6">
            <div 
                className="absolute inset-0 h-full w-full bg-cover bg-center z-0 opacity-10" 
                style={{ backgroundImage: "url(https://i.imgur.com/YSuDJBG.png)" }}
            ></div>
            <div className="absolute inset-0 bg-gradient-to-t from-black via-black/90 to-black z-10"></div>
            
            <div className="relative z-20 w-full max-w-3xl mx-auto text-center">
                <header className="mb-12 animate-fade-in-up">
                    <h1 className="font-editorial text-4xl sm:text-5xl md:text-6xl text-white tracking-wider mb-4">{t('conceito.title')}</h1>
                    <p className="font-technical text-gray-500 max-w-2xl mx-auto">{t('conceito.subtitle')}</p>
                </header>

                {!result && !error && (
                    <div className="w-full animate-fade-in-up delay-200">
                        <p className="text-gray-400 mb-8 max-w-xl mx-auto">{t('conceito.intro')}</p>
                        <textarea
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            placeholder={t('conceito.placeholder')}
                            className="w-full h-40 bg-gray-900/50 border border-gray-700 text-gray-300 p-4 font-technical focus:outline-none focus:ring-2 focus:ring-yellow-300/50 resize-none"
                            disabled={isLoading}
                        />
                        <button
                            onClick={handleGenerate}
                            disabled={isLoading || !prompt.trim()}
                            className="group mt-6 w-full max-w-md mx-auto flex items-center justify-center gap-3 font-editorial uppercase tracking-widest text-lg border-2 border-yellow-300 text-black bg-yellow-300 px-10 py-4 hover:bg-transparent hover:text-yellow-300 transition-all duration-300 ease-in-out disabled:bg-gray-600 disabled:border-gray-600 disabled:text-gray-400 disabled:cursor-not-allowed"
                        >
                            <TerminalIcon className="w-5 h-5 transition-colors duration-300 text-black group-hover:text-yellow-300" />
                            <span>{isLoading ? t('conceito.button_generating') : t('conceito.button_generate')}</span>
                        </button>
                        {impatientMessage && <p className="text-xs text-gray-700 mt-4 animate-fade-in-up">{impatientMessage}</p>}
                    </div>
                )}

                {(result || error) && (
                    <div className="w-full animate-fade-in-up text-left border border-gray-800 bg-black/50 p-8">
                        <h2 className="font-editorial text-2xl text-yellow-300 tracking-wider mb-6">{t('conceito.result_title')}</h2>
                        {error && <p className="text-red-400">{error}</p>}
                        {result && <div className="prose prose-invert prose-p:text-gray-300 prose-headings:text-white prose-headings:font-editorial" dangerouslySetInnerHTML={{ __html: result.replace(/\n/g, '<br/>') }} />}
                        
                        <button onClick={handleBack} className="mt-8 text-yellow-300 hover:underline font-technical">{t('shared.back')}</button>

                        {result && <ConceptContactForm conceptText={result} onBack={handleBack} />}
                    </div>
                )}
            </div>
        </div>
    );
};

export default Conceito;
