
import React, { useState } from 'react';
import { GoogleGenAI, GenerateContentResponse } from '@google/genai';
import { useLanguage } from '../../context/LanguageContext';
import { TerminalIcon } from '../icons/TerminalIcon';

declare const Forminit: any;

type ResultState = {
    message: string;
    type: 'success' | 'error';
} | null;

const ConceptContactForm: React.FC<{ conceptText: string; onBack: () => void; }> = ({ conceptText, onBack }) => {
    const { language, t } = useLanguage();
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [result, setResult] = useState<ResultState>(null);
    const [countryCode, setCountryCode] = useState('');
    const [contactMethod, setContactMethod] = useState('WhatsApp');
    const FORM_ID = "u1v5ddm2e7d";

    const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault();
        setResult(null);

        const formElement = e.target as HTMLFormElement;
        const formData = new FormData(formElement);
        
        const fullMessage = `--- CONCEPT SHEET GENERATED BY VRT_AI ---\n\n${conceptText}`;
        formData.append('fi-text-message', fullMessage);
        
        const phoneInput = formData.get('fi-sender-phone') as string || '';

        setIsSubmitting(true);
        
        if (phoneInput.trim()) {
            if (language === 'en') {
                const fullPhone = `+${countryCode || '1'} ${phoneInput} (Contact via ${contactMethod})`;
                formData.set('fi-sender-phone', fullPhone);
            } else if (language === 'pt') {
                const justDigits = phoneInput.replace(/\D/g, '');
                formData.set('fi-sender-phone', `+55${justDigits}`);
            }
        }

        try {
            const forminit = new Forminit();
            const { error } = await forminit.submit(FORM_ID, formData);

            if (error) {
                throw new Error(error.message || t('contato.form.error_submit'));
            }

            setResult({ message: t('contato.form.success_direct'), type: 'success' });
            formElement.reset();
        } catch (err: any) {
            setResult({ message: err.message || t('contato.form.error_submit'), type: 'error' });
        } finally {
            setIsSubmitting(false);
        }
    };

    return (
        <div className="mt-12 text-center border-t border-gray-800 pt-8 animate-fade-in-up">
            <h3 className="font-editorial text-2xl text-white">{t('conceito.cta_title')}</h3>
            <p className="text-gray-500 max-w-xl mx-auto mt-2 mb-6">{t('conceito.cta_text')}</p>
            
            {result?.type === 'success' ? (
                <div className="p-4 bg-green-500/10 text-green-300 text-center">
                    <p>{result.message}</p>
                    <button onClick={onBack} className="mt-4 text-yellow-300 underline">{t('shared.back')}</button>
                </div>
            ) : (
                <form id="concept-contact-form" onSubmit={handleSubmit} className="space-y-6 text-left max-w-xl mx-auto">
                    <div className="flex flex-col sm:flex-row gap-6">
                        <div className="flex-1">
                            <label htmlFor="fi-sender-firstName" className="block text-sm text-gray-400 mb-2">{t('contato.form.first_name_label')}</label>
                            <input type="text" name="fi-sender-firstName" id="fi-sender-firstName" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                        <div className="flex-1">
                            <label htmlFor="fi-sender-lastName" className="block text-sm text-gray-400 mb-2">{t('contato.form.last_name_label')}</label>
                            <input type="text" name="fi-sender-lastName" id="fi-sender-lastName" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                    </div>
                     <div className="flex flex-col sm:flex-row gap-6">
                        <div className="flex-1">
                            <label htmlFor="fi-sender-email" className="block text-sm text-gray-400 mb-2">{t('contato.form.email_label')}</label>
                            <input type="email" name="fi-sender-email" id="fi-sender-email" required className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                        </div>
                         {language === 'en' ? (
                            <div className="flex-1 flex gap-2">
                                <div className="w-1/3">
                                    <label htmlFor="country-code" className="block text-sm text-gray-400 mb-2">{t('contato.form.country_code_label')}</label>
                                    <input type="text" id="country-code" value={countryCode} onChange={e => setCountryCode(e.target.value.replace(/\D/g, ''))} placeholder="+1" className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                                </div>
                                <div className="flex-1">
                                    <label htmlFor="fi-sender-phone" className="block text-sm text-gray-400 mb-2">{t('contato.form.phone_label')}</label>
                                    <input type="tel" name="fi-sender-phone" id="fi-sender-phone" className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                                </div>
                            </div>
                        ) : (
                            <div className="flex-1">
                                <label htmlFor="fi-sender-phone" className="block text-sm text-gray-400 mb-2">{t('contato.form.phone_label')}</label>
                                <input type="tel" name="fi-sender-phone" id="fi-sender-phone" placeholder={t('contato.form.phone_placeholder')} className="w-full bg-gray-900/50 border border-gray-700 text-white p-3 focus:outline-none focus:ring-2 focus:ring-yellow-300/50" />
                            </div>
                        )}
                    </div>
                    {language === 'en' && (
                        <div>
                            <label className="block text-sm text-gray-400 mb-2">{t('contato.form.contact_method_label')}</label>
                            <div className="flex gap-6 items-center">
                                <label className="flex items-center gap-2 text-gray-300 cursor-pointer">
                                    <input type="radio" name="contactMethod" value="WhatsApp" checked={contactMethod === 'WhatsApp'} onChange={() => setContactMethod('WhatsApp')} className="accent-yellow-300" />
                                    {t('contato.form.contact_method_whatsapp')}
                                </label>
                                <label className="flex items-center gap-2 text-gray-300 cursor-pointer">
                                    <input type="radio" name="contactMethod" value="Call" checked={contactMethod === 'Call'} onChange={() => setContactMethod('Call')} className="accent-yellow-300" />
                                    {t('contato.form.contact_method_call')}
                                </label>
                            </div>
                        </div>
                    )}
                    <button type="submit" disabled={isSubmitting} className="w-full font-editorial uppercase tracking-widest text-lg border-2 border-yellow-300 text-black bg-yellow-300 px-10 py-4 hover:bg-transparent hover:text-yellow-300 transition-all duration-300 ease-in-out disabled:bg-gray-600">
                        {isSubmitting ? t('contato.form.submitting') : t('contato.form.send')}
                    </button>
                     {result?.type === 'error' && (
                        <p className="mt-4 text-red-400 text-center">{result.message}</p>
                    )}
                </form>
            )}
        </div>
    );
};

const Conceito: React.FC = () => {
    const { t, language } = useLanguage();
    const [prompt, setPrompt] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [result, setResult] = useState('');
    const [error, setError] = useState('');
    const [showContactForm, setShowContactForm] = useState(false);
    const [impatientClicks, setImpatientClicks] = useState(0);
    const [ironicButtonText, setIronicButtonText] = useState('');
    
    const apiKey = process.env.API_KEY;

    const systemInstructions = {
        en: `You are 'Terminal', VERTICE's lead project consultant AI. Your task is to translate a user's dream car description into a structured and inspiring "Concept Sheet". Your tone must be technical, insightful, and philosophical, echoing the VERTICE brand.
        
        The user will provide a prompt. You must generate a response in Markdown format with the following structure:
        
        ### **PROJECT NAME:** [Invent a creative, evocative name for the project]
        
        ---
        
        #### **PHILOSOPHY**
        [Write a short paragraph capturing the core emotional and philosophical goal of the build. What is its purpose beyond being a car?]
        
        ---
        
        #### **AESTHETIC & STANCE**
        *   **Exterior:** [Describe the visual approach. Mention color, texture, and key body modifications.]
        *   **Interior:** [Describe the cabin's atmosphere. Focus on driver connection, materials, and minimalism.]
        *   **Stance:** [Describe its posture. How it sits on the road. Use words like 'aggressive', 'poised', 'functional'.]
        
        ---
        
        #### **TECHNICAL BLUEPRINT**
        *   **Powertrain:** [Suggest a specific engine and drivetrain philosophy. Mention the target feel, not just specs.]
        *   **Suspension & Handling:** [Recommend a suspension setup that matches the philosophy. Is it for track precision or for spirited road carving?]
        *   **Braking System:** [Suggest a suitable braking system to balance the power.]
        *   **Electronics:** [Mention the role of the ECU and any custom wiring needed to achieve reliability and performance.]
        
        ---
        
        #### **X-FACTOR**
        [Describe the one unique, defining element that makes this project a true VERTICE build. It could be a custom-fabricated part, a unique sound signature, or a specific sensory detail.]`,
        pt: `Você é o 'Terminal', o principal consultor de projetos de IA da VERTICE. Sua tarefa é traduzir a descrição do carro dos sonhos de um usuário em uma "Ficha de Conceito" estruturada e inspiradora. Seu tom deve ser técnico, perspicaz e filosófico, ecoando a marca VERTICE.

        O usuário fornecerá um prompt. Você deve gerar uma resposta em formato Markdown com a seguinte estrutura:
        
        ### **NOME DO PROJETO:** [Invente um nome criativo e evocativo para o projeto]
        
        ---
        
        #### **FILOSOFIA**
        [Escreva um parágrafo curto capturando o objetivo emocional e filosófico central da construção. Qual é o seu propósito além de ser um carro?]
        
        ---
        
        #### **ESTÉTICA & POSTURA**
        *   **Exterior:** [Descreva a abordagem visual. Mencione cor, textura e modificações principais na carroceria.]
        *   **Interior:** [Descreva a atmosfera da cabine. Foque na conexão do piloto, materiais e minimalismo.]
        *   **Postura:** [Descreva sua postura. Como ele se assenta na estrada. Use palavras como 'agressiva', 'equilibrada', 'funcional'.]
        
        ---
        
        #### **BLUEPRINT TÉCNICO**
        *   **Powertrain:** [Sugira um motor específico e uma filosofia de transmissão. Mencione a sensação alvo, não apenas especificações.]
        *   **Suspensão & Dirigibilidade:** [Recomende uma configuração de suspensão que corresponda à filosofia. É para precisão em pista ou para uma condução espirituosa na estrada?]
        *   **Sistema de Freios:** [Sugira um sistema de freios adequado para equilibrar a potência.]
        *   **Eletrônica:** [Mencione o papel da ECU e qualquer fiação customizada necessária para alcançar confiabilidade e performance.]
        
        ---
        
        #### **FATOR X**
        [Descreva o elemento único e definidor que torna este projeto uma verdadeira construção VERTICE. Pode ser uma peça fabricada sob medida, uma assinatura sonora única ou um detalhe sensorial específico.]`
    };

    const handleGenerate = async () => {
        if (!prompt.trim() || !apiKey) return;
        
        const ai = new GoogleGenAI({ apiKey });

        setIsLoading(true);
        setResult('');
        setError('');
        setShowContactForm(false);
        setImpatientClicks(0);
        try {
            const response: GenerateContentResponse = await ai.models.generateContent({
                model: 'gemini-3-flash-preview',
                contents: [{ role: 'user', parts: [{ text: prompt }] }],
                config: { systemInstruction: systemInstructions[language] },
            });
            setResult(response.text ?? '');
        } catch (e) {
            console.error(e);
            setError(t('conceito.error_message'));
        } finally {
            setIsLoading(false);
        }
    };

    const handleButtonClick = () => {
        if (isLoading) {
            const newCount = impatientClicks + 1;
            setImpatientClicks(newCount);
            if (newCount >= 4 && !ironicButtonText) {
                const messages = t('easter_eggs.concept_impatient_clicks').split('|');
                const randomMessage = messages[Math.floor(Math.random() * messages.length)];
                setIronicButtonText(randomMessage);
                setTimeout(() => {
                    setIronicButtonText('');
                    setImpatientClicks(0);
                }, 3000);
            }
            return;
        }

        if (!prompt.trim() || !apiKey) {
            return;
        }
        
        handleGenerate();
    };
    
    // Simple markdown to HTML renderer
    const renderMarkdown = (text: string) => {
        const html = text
            .replace(/###\s*(.*?)\s*$/gm, '<h3 class="font-editorial text-2xl text-white mt-8 mb-4">$1</h3>')
            .replace(/####\s*(.*?)\s*$/gm, '<h4 class="font-editorial text-lg text-yellow-300 mt-6 mb-3">$1</h4>')
            .replace(/^\*\s*(.*?)\s*$/gm, '<li class="ml-6">$1</li>')
            .replace(/---/g, '<hr class="border-gray-800 my-6">')
            .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');

        return <div dangerouslySetInnerHTML={{ __html: html }} className="prose-styles" />;
    };

    const isEffectivelyDisabled = (!prompt.trim() && !isLoading) || !apiKey;

    return (
        <div className="min-h-screen w-full relative py-20 md:py-28 bg-black">
            <div 
                className="absolute inset-0 h-full w-full z-0 bg-cover bg-center opacity-20" 
                style={{ backgroundImage: "url(https://i.imgur.com/4bzpSbj.png)" }}
            ></div>
            <div className="absolute inset-0 bg-gradient-to-t from-black via-black/80 to-black z-10"></div>
            
            <div className="relative z-20 container mx-auto px-6">
                <header className="text-center max-w-3xl mx-auto animate-fade-in-up-elegant">
                    <h1 className="font-editorial text-4xl sm:text-5xl md:text-6xl text-white tracking-wider mb-4">{t('conceito.title')}</h1>
                    <p className="font-technical uppercase text-gray-500 tracking-[0.3em] text-sm">{t('conceito.subtitle')}</p>
                </header>

                <main className="max-w-4xl mx-auto mt-12 md:mt-16">
                    <div className="bg-black/50 border border-gray-900 p-8 animate-fade-in-up-elegant delay-200">
                        <p className="text-gray-400 leading-relaxed mb-6 text-center">{t('conceito.intro')}</p>
                        <textarea
                            value={prompt}
                            onChange={(e) => setPrompt(e.target.value)}
                            placeholder={t('conceito.placeholder')}
                            rows={6}
                            className="w-full bg-gray-900/70 border border-gray-800 p-4 text-gray-300 focus:outline-none focus:ring-2 focus:ring-yellow-300/50 transition-all duration-300 font-technical"
                            disabled={isLoading || !apiKey}
                        />
                         {!apiKey && (
                            <p className="text-center text-red-500/70 text-xs mt-2">AI Concept Builder is unavailable: API Key not configured.</p>
                        )}
                        <button
                            onClick={handleButtonClick}
                            disabled={isEffectivelyDisabled}
                            className={`group mt-6 w-full flex items-center justify-center gap-3 font-editorial uppercase tracking-widest text-lg border-2 px-10 py-4 transition-all duration-300 ease-in-out ${isEffectivelyDisabled ? 'bg-gray-800 border-gray-800 text-gray-600 cursor-not-allowed' : 'border-yellow-300 text-black bg-yellow-300 hover:bg-transparent hover:text-yellow-300'}`}
                        >
                            <TerminalIcon className="w-5 h-5 transition-colors duration-300 text-black group-hover:text-yellow-300" />
                            <span>{isLoading ? (ironicButtonText || t('conceito.button_generating')) : t('conceito.button_generate')}</span>
                        </button>
                    </div>

                    {(result || error) && (
                        <div className="mt-12 bg-black/50 border border-gray-900 p-8 md:p-12 animate-fade-in-up-elegant">
                            {error ? (
                                <p className="text-red-400 text-center">{error}</p>
                            ) : (
                                <>
                                    <h2 className="font-technical text-yellow-300 text-center uppercase tracking-[0.2em] mb-8">{t('conceito.result_title')}</h2>
                                    <div className="text-gray-300 leading-relaxed space-y-4 font-technical">
                                      {renderMarkdown(result)}
                                    </div>

                                    {showContactForm ? (
                                        <ConceptContactForm conceptText={result} onBack={() => setShowContactForm(false)} />
                                    ) : (
                                        <div className="mt-12 text-center border-t border-gray-800 pt-8">
                                            <h3 className="font-editorial text-2xl text-white">{t('conceito.cta_title')}</h3>
                                            <p className="text-gray-500 max-w-xl mx-auto mt-2 mb-6">{t('conceito.cta_text')}</p>
                                            <button 
                                                onClick={() => setShowContactForm(true)}
                                                className="inline-block font-editorial uppercase tracking-widest text-base border border-yellow-300 text-yellow-300 px-8 py-3 hover:bg-yellow-300 hover:text-black transition-all duration-300 ease-in-out"
                                            >
                                               {t('conceito.cta_button')}
                                            </button>
                                        </div>
                                    )}
                                </>
                            )}
                        </div>
                    )}
                </main>
            </div>
        </div>
    );
};

export default Conceito;
